services:
  server:
    build:
      context: ../
      dockerfile: ./docker/server.Dockerfile
  client1:
    build:
      context: ../
      dockerfile: ./docker/client.Dockerfile
  client2:
    build:
      context: ../
      dockerfile: ./docker/client.Dockerfile
