services:
  server:
    network_mode: host
    environment:
      SERVER_PORT: "8000"
    build:
      context: ../
      dockerfile: ./docker/server.Dockerfile
  client1:
    network_mode: host
    environment:
      CLIENT_PORT: "8080"
    build:
      context: ../
      dockerfile: ./docker/client.Dockerfile
  client2:
    network_mode: host
    environment:
      CLIENT_PORT: "8081"
    build:
      context: ../
      dockerfile: ./docker/client.Dockerfile
